INITIAL_CAREERS = [
    {"title": "Frontend Developer", "category": "Teknologi (IT)",
     "description": "Frontend Developer membangun antarmuka pengguna website dan aplikasi web menggunakan HTML, CSS, dan JavaScript.",
     "common_tasks": ["Menerjemahkan desain ke kode", "Optimasi performa frontend", "Integrasi API"],
     "required_skills": ["HTML", "CSS", "JavaScript", "React/Vue", "Git"],
     "optional_skills": ["TypeScript", "Tailwind CSS", "Testing"],
     "education_paths": ["S1 Ilmu Komputer", "Bootcamp Coding", "D3 Teknik Informatika"],
     "salary_min": "Rp5.000.000", "salary_max": "Rp18.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "Backend Developer", "category": "Teknologi (IT)",
     "description": "Backend Developer mengembangkan logika server, API, dan database yang mendukung aplikasi.",
     "common_tasks": ["Membangun REST API", "Desain database", "Optimasi query"],
     "required_skills": ["Python/Node.js", "SQL", "REST API", "Git"],
     "optional_skills": ["Docker", "Cloud (AWS/GCP)", "Message Queue"],
     "education_paths": ["S1 Ilmu Komputer", "Bootcamp Coding"],
     "salary_min": "Rp5.000.000", "salary_max": "Rp20.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "UI/UX Designer", "category": "Teknologi (IT)",
     "description": "UI/UX Designer merancang antarmuka dan pengalaman pengguna yang intuitif dan menarik.",
     "common_tasks": ["Riset pengguna", "Wireframing", "Pembuatan prototipe", "Usability testing"],
     "required_skills": ["Figma", "Design Thinking", "Riset Pengguna"],
     "optional_skills": ["HTML/CSS", "Motion Design", "Illustrator"],
     "education_paths": ["S1 Desain Komunikasi Visual", "Bootcamp UI/UX", "S1 Psikologi"],
     "salary_min": "Rp5.500.000", "salary_max": "Rp16.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "Data Analyst", "category": "Teknologi (IT)",
     "description": "Data Analyst mengolah data untuk menghasilkan insight yang mendukung keputusan bisnis.",
     "common_tasks": ["Pengumpulan data", "Pembersihan data", "Visualisasi", "Pelaporan"],
     "required_skills": ["SQL", "Excel", "Python/R", "Visualisasi Data"],
     "optional_skills": ["Tableau/Power BI", "Machine Learning", "Statistika"],
     "education_paths": ["S1 Statistika", "S1 Matematika", "S1 Sistem Informasi"],
     "salary_min": "Rp5.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang"},
    {"title": "Data Scientist", "category": "Teknologi (IT)",
     "description": "Data Scientist menggunakan machine learning dan analisis statistik untuk memecahkan masalah kompleks.",
     "common_tasks": ["Eksplorasi data", "Pembangunan model ML", "Evaluasi model", "Deployment"],
     "required_skills": ["Python", "Machine Learning", "Statistika", "SQL"],
     "optional_skills": ["Deep Learning", "Cloud Platform", "MLOps"],
     "education_paths": ["S1 Ilmu Komputer", "S1 Matematika/Statistika", "S2 Data Science"],
     "salary_min": "Rp8.000.000", "salary_max": "Rp30.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang"},
    {"title": "Mobile Developer", "category": "Teknologi (IT)",
     "description": "Mobile Developer membangun aplikasi mobile untuk Android dan iOS.",
     "common_tasks": ["Mengembangkan fitur aplikasi", "Integrasi API", "Testing", "Rilis ke app store"],
     "required_skills": ["Kotlin/Swift", "API Integration", "Git"],
     "optional_skills": ["Flutter/React Native", "UI/UX", "CI/CD"],
     "education_paths": ["S1 Ilmu Komputer", "Bootcamp Mobile"],
     "salary_min": "Rp6.000.000", "salary_max": "Rp20.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "Cyber Security Analyst", "category": "Teknologi (IT)",
     "description": "Cyber Security Analyst melindungi sistem dan data organisasi dari ancaman siber.",
     "common_tasks": ["Monitoring keamanan", "Penetration testing", "Incident response"],
     "required_skills": ["Jaringan", "Sistem Operasi", "Keamanan Informasi"],
     "optional_skills": ["Sertifikasi CEH/CISSP", "Python", "Forensik Digital"],
     "education_paths": ["S1 Ilmu Komputer", "S1 Keamanan Informasi", "Sertifikasi"],
     "salary_min": "Rp7.000.000", "salary_max": "Rp25.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "DevOps Engineer", "category": "Teknologi (IT)",
     "description": "DevOps Engineer mengelola infrastruktur dan pipeline deployment untuk pengembangan software.",
     "common_tasks": ["CI/CD pipeline", "Container management", "Infrastructure as Code", "Monitoring"],
     "required_skills": ["Linux", "Docker", "CI/CD", "Cloud Services"],
     "optional_skills": ["Kubernetes", "Terraform", "Ansible"],
     "education_paths": ["S1 Ilmu Komputer", "Bootcamp DevOps"],
     "salary_min": "Rp8.000.000", "salary_max": "Rp25.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "QA Engineer", "category": "Teknologi (IT)",
     "description": "QA Engineer memastikan kualitas software melalui pengujian manual dan otomatis.",
     "common_tasks": ["Membuat test case", "Manual testing", "Automation testing", "Bug tracking"],
     "required_skills": ["Testing Methodology", "Bug Tracking", "SQL"],
     "optional_skills": ["Selenium/Cypress", "Python", "CI/CD"],
     "education_paths": ["S1 Ilmu Komputer", "Bootcamp QA", "D3 Teknik Informatika"],
     "salary_min": "Rp4.500.000", "salary_max": "Rp14.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang"},
    {"title": "IT Support", "category": "Teknologi (IT)",
     "description": "IT Support memberikan bantuan teknis kepada pengguna dan memelihara infrastruktur IT.",
     "common_tasks": ["Troubleshooting hardware/software", "Instalasi sistem", "Manajemen jaringan"],
     "required_skills": ["Windows/Linux", "Jaringan Dasar", "Troubleshooting"],
     "optional_skills": ["Database", "Cloud Basic", "Sertifikasi IT"],
     "education_paths": ["D3 Teknik Informatika", "S1 Sistem Informasi", "Sertifikasi"],
     "salary_min": "Rp3.500.000", "salary_max": "Rp8.000.000", "market_prospect": "Sedang", "ai_risk": "Rendah"},
    {"title": "Content Creator", "category": "Kreatif & Media",
     "description": "Content Creator memproduksi konten digital untuk platform media sosial dan website.",
     "common_tasks": ["Riset topik", "Produksi konten", "Editing", "Analisis engagement"],
     "required_skills": ["Menulis", "Fotografi/Video", "Social Media", "Editing"],
     "optional_skills": ["SEO", "Copywriting", "Public Speaking"],
     "education_paths": ["S1 Komunikasi", "S1 Desain", "Otodidak/Bootcamp"],
     "salary_min": "Rp3.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang"},
    {"title": "Graphic Designer", "category": "Kreatif & Media",
     "description": "Graphic Designer menciptakan desain visual untuk media cetak dan digital.",
     "common_tasks": ["Desain logo/branding", "Layout cetak/digital", "Ilustrasi"],
     "required_skills": ["Adobe Photoshop", "Adobe Illustrator", "Typography", "Warna"],
     "optional_skills": ["Motion Design", "3D", "Photography"],
     "education_paths": ["S1 Desain Komunikasi Visual", "D3 Desain Grafis"],
     "salary_min": "Rp4.000.000", "salary_max": "Rp12.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang"},
    {"title": "Video Editor", "category": "Kreatif & Media",
     "description": "Video Editor mengedit dan memproduksi konten video untuk berbagai platform.",
     "common_tasks": ["Editing video", "Color grading", "Sound design", "Efek visual"],
     "required_skills": ["Adobe Premiere Pro", "After Effects", "Storytelling"],
     "optional_skills": ["Motion Graphics", "Color Grading", "Videography"],
     "education_paths": ["S1 Film/Televisi", "D3 Multimedia", "Bootcamp"],
     "salary_min": "Rp4.000.000", "salary_max": "Rp12.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang"},
    {"title": "Social Media Specialist", "category": "Kreatif & Media",
     "description": "Social Media Specialist mengelola strategi konten dan engagement di platform media sosial.",
     "common_tasks": ["Perencanaan konten", "Copywriting", "Analisis metrics", "Community management"],
     "required_skills": ["Social Media Platform", "Copywriting", "Analytics", "Content Planning"],
     "optional_skills": ["Graphic Design", "Videography", "SEO"],
     "education_paths": ["S1 Komunikasi", "S1 Marketing", "Bootcamp"],
     "salary_min": "Rp4.000.000", "salary_max": "Rp10.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang"},
    {"title": "Dokter Umum", "category": "Kesehatan",
     "description": "Dokter Umum mendiagnosis dan menangani penyakit umum serta memberikan pelayanan kesehatan primer.",
     "common_tasks": ["Pemeriksaan pasien", "Diagnosis", "Resep obat", "Edukasi kesehatan"],
     "required_skills": ["Pengetahuan Medis", "Diagnosis", "Komunikasi", "Empati"],
     "optional_skills": ["Manajemen Klinik", "Penelitian", "Bahasa Asing"],
     "education_paths": ["S1 Kedokteran + Profesi Dokter", "PPDS (Spesialisasi)"],
     "salary_min": "Rp7.000.000", "salary_max": "Rp25.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "Perawat", "category": "Kesehatan",
     "description": "Perawat memberikan asuhan keperawatan kepada pasien di rumah sakit dan fasilitas kesehatan.",
     "common_tasks": ["Perawatan pasien", "Administrasi obat", "Monitoring vital sign"],
     "required_skills": ["Keperawatan Dasar", "Komunikasi", "Emergency Response"],
     "optional_skills": ["Manajemen Ruangan", "Bahasa Asing"],
     "education_paths": ["D3 Keperawatan", "S1 Keperawatan + Ners"],
     "salary_min": "Rp3.500.000", "salary_max": "Rp10.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "Apoteker", "category": "Kesehatan",
     "description": "Apoteker menyiapkan dan memberikan obat serta memberikan informasi mengenai penggunaan obat.",
     "common_tasks": ["Peracikan obat", "Konseling obat", "Manajemen apotek"],
     "required_skills": ["Farmakologi", "Manajemen Obat", "Komunikasi"],
     "optional_skills": ["Penelitian", "Manajemen Bisnis"],
     "education_paths": ["S1 Farmasi + Profesi Apoteker"],
     "salary_min": "Rp5.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "Guru SD", "category": "Pendidikan",
     "description": "Guru SD mengajar mata pelajaran dasar dan membimbing perkembangan siswa sekolah dasar.",
     "common_tasks": ["Mengajar", "Membuat RPP", "Evaluasi siswa", "Komunikasi orang tua"],
     "required_skills": ["Pedagogi", "Komunikasi", "Kesabaran", "Kreativitas"],
     "optional_skills": ["Bimbingan Konseling", "Teknologi Pendidikan"],
     "education_paths": ["S1 PGSD", "S1 Pendidikan", "PPG"],
     "salary_min": "Rp2.500.000", "salary_max": "Rp7.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "Dosen", "category": "Pendidikan",
     "description": "Dosen mengajar dan melakukan penelitian di perguruan tinggi.",
     "common_tasks": ["Mengajar", "Penelitian", "Publikasi ilmiah", "Pengabdian masyarakat"],
     "required_skills": ["Penelitian", "Publikasi", "Pengajaran", "Komunikasi"],
     "optional_skills": ["Bahasa Asing", "Statistika", "Jurnalistik Ilmiah"],
     "education_paths": ["S2 (Minimal)", "S3", "Sertifikasi Dosen"],
     "salary_min": "Rp4.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang"},
    {"title": "Digital Marketing", "category": "Bisnis & Marketing",
     "description": "Digital Marketing mengelola strategi pemasaran online untuk meningkatkan brand awareness dan penjualan.",
     "common_tasks": ["SEO/SEM", "Social media ads", "Email marketing", "Analytics"],
     "required_skills": ["SEO", "Google Ads", "Social Media Ads", "Analytics"],
     "optional_skills": ["Copywriting", "Design", "Content Strategy"],
     "education_paths": ["S1 Marketing", "S1 Komunikasi", "Bootcamp Digital Marketing"],
     "salary_min": "Rp4.500.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang"},
    {"title": "Akuntan", "category": "Keuangan & Hukum",
     "description": "Akuntan mengelola pencatatan keuangan, audit, dan pelaporan pajak untuk perusahaan atau klien.",
     "common_tasks": ["Pembukuan", "Laporan keuangan", "Audit", "Perpajakan"],
     "required_skills": ["Akuntansi", "Pajak", "Excel", "Software Akuntansi"],
     "optional_skills": ["Audit", "Analisis Keuangan", "SAP/Oracle"],
     "education_paths": ["S1 Akuntansi", "PPAk (Pendidikan Profesi Akuntansi)"],
     "salary_min": "Rp4.500.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang"},
    {"title": "PNS Administrasi", "category": "Pemerintahan & BUMN",
     "description": "PNS Administrasi melaksanakan tugas ketatausahaan dan pelayanan publik di instansi pemerintah.",
     "common_tasks": ["Administrasi surat", "Pelayanan publik", "Pelaporan"],
     "required_skills": ["Administrasi", "Komunikasi", "Microsoft Office"],
     "optional_skills": ["Manajemen Arsip", "Hukum Administrasi"],
     "education_paths": ["S1 Semua Jurusan", "Tes CPNS"],
     "salary_min": "Rp3.000.000", "salary_max": "Rp10.000.000", "market_prospect": "Stabil", "ai_risk": "Rendah"},
    {"title": "Wirausaha", "category": "Bisnis & Marketing",
     "description": "Wirausaha memulai dan mengelola bisnis sendiri, dari perencanaan hingga eksekusi.",
     "common_tasks": ["Perencanaan bisnis", "Manajemen operasional", "Pemasaran", "Keuangan"],
     "required_skills": ["Leadership", "Manajemen", "Pemasaran", "Problem Solving"],
     "optional_skills": ["Digital Marketing", "Keuangan", "Networking"],
     "education_paths": ["Pengalaman Lapangan", "S1 Manajemen/Bisnis", "Bootcamp"],
     "salary_min": "Rp2.000.000", "salary_max": "Rp50.000.000", "market_prospect": "Variatif", "ai_risk": "Sedang"},
    {"title": "Teknik Sipil", "category": "Teknik non-IT",
     "description": "Teknik Sipil merancang, membangun, dan memelihara infrastruktur seperti gedung, jembatan, dan jalan.",
     "common_tasks": ["Perencanaan konstruksi", "Pengawasan proyek", "Manajemen material"],
     "required_skills": ["AutoCAD", "Struktur", "Manajemen Proyek"],
     "optional_skills": ["SAP2000/ETABS", "Revit", "Estimasi Biaya"],
     "education_paths": ["S1 Teknik Sipil"],
     "salary_min": "Rp5.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah"},
    {"title": "Arsitek", "category": "Teknik non-IT",
     "description": "Arsitek merancang bangunan dan ruang yang estetis, fungsional, dan aman.",
     "common_tasks": ["Desain bangunan", "Gambar teknis", "Koordinasi kontraktor"],
     "required_skills": ["AutoCAD", "SketchUp/Revit", "Desain"],
     "optional_skills": ["3D Rendering", "Sustainable Design", "Manajemen Proyek"],
     "education_paths": ["S1 Arsitektur"],
     "salary_min": "Rp5.000.000", "salary_max": "Rp18.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang"},
    {"title": "Tour Guide", "category": "Jasa & Pariwisata",
     "description": "Tour Guide memandu wisatawan dan memberikan informasi tentang objek wisata.",
     "common_tasks": ["Memandu tur", "Informasi wisata", "Koordinasi logistik"],
     "required_skills": ["Bahasa Inggris", "Komunikasi", "Pengetahuan Lokal"],
     "optional_skills": ["Bahasa Asing Lain", "Fotografi", "First Aid"],
     "education_paths": ["D3 Pariwisata", "S1 Pariwisata", "Sertifikasi Pramuwisata"],
     "salary_min": "Rp2.500.000", "salary_max": "Rp8.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang"},
    {"title": "Petani Modern", "category": "Pertanian & Kelautan",
     "description": "Petani Modern menggunakan teknologi dan metode pertanian terkini untuk meningkatkan hasil panen.",
     "common_tasks": ["Perencanaan tanam", "Penggunaan teknologi pertanian", "Manajemen hasil"],
     "required_skills": ["Agrikultur", "Manajemen", "Teknologi Pertanian"],
     "optional_skills": ["Hidroponik", "IoT", "Pemasaran Digital"],
     "education_paths": ["S1 Agribisnis", "S1 Pertanian", "Pelatihan"],
     "salary_min": "Rp3.000.000", "salary_max": "Rp10.000.000", "market_prospect": "Sedang", "ai_risk": "Rendah"},
]

CATEGORIES = [
    "Teknologi (IT)", "Kesehatan", "Pendidikan", "Pemerintahan & BUMN",
    "Kreatif & Media", "Bisnis & Marketing", "Teknik non-IT",
    "Keuangan & Hukum", "Jasa & Pariwisata", "Pertanian & Kelautan"
]
