"""Initial career data for Life Compass v2 — expanded with v2 fields."""

INITIAL_CAREERS = []

# Helper: generate default v2 fields for any career
def _v2_career(base: dict) -> dict:
    defaults = {
        "subcategories": [],
        "aliases": [],
        "day_in_the_life": None,
        "common_misconceptions": [],
        "soft_skills": ["Komunikasi", "Kerja Tim", "Pemecahan Masalah"],
        "anti_skills": [],
        "alternative_paths": [],
        "path_success_rates": None,
        "credential_weight": 3,
        "salary_entry": None,
        "salary_mid": None,
        "salary_senior": None,
        "income_trajectory": "linear",
        "global_demand": "Sedang",
        "growth_rate_5yr": "+5-10%",
        "saturation_risk": "Rendah",
        "ai_displacement_score": 0.25,
        "ai_displacement_timeline": "5-10 tahun",
        "ai_affected_tasks": [],
        "ai_resilient_tasks": [],
        "remote_availability": "Rendah",
        "geographic_hotspots": [],
        "entry_barriers": [],
        "time_to_first_job": None,
        "interview_difficulty": 2,
        "typical_application_count": "20-50",
        "gatekeeping_factors": [],
        "experience_catch_22": 2,
        "career_ladder": [],
        "time_to_senior": "3-5 tahun",
        "time_to_expert": "7-10 tahun",
        "management_track": False,
        "ic_track": True,
        "entrepreneurial_exit": "Rendah",
        "common_pivots_from": [],
        "common_pivots_to": [],
        "adjacent_careers": [],
        "bridge_careers": [],
        "aspiration_careers": [],
        "specialization_options": [],
        "typical_team_size": "2-5 orang",
        "pace": "sedang",
        "autonomy_level": 3,
        "feedback_frequency": "bulanan",
        "learning_culture": 3,
        "bureaucracy_level": 3,
        "work_life_balance": 3,
        "travel_requirement": "none",
        "thrives_on": [],
        "struggles_with": [],
        "holland_codes": [],
        "burnout_risk_factors": [],
        "longevity_predictors": [],
        "source_notes": [],
        "status": "published",
    }
    defaults.update(base)
    return defaults

# ──────────────────────────────────────────
# TECHNOLOGY (IT)
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Frontend Developer", "category": "Teknologi (IT)",
        "description": "Frontend Developer membangun antarmuka pengguna website dan aplikasi web menggunakan HTML, CSS, dan JavaScript.",
        "common_tasks": ["Menerjemahkan desain ke kode", "Optimasi performa frontend", "Integrasi API", "Code review", "Responsive design"],
        "required_skills": ["HTML", "CSS", "JavaScript", "React/Vue", "Git"],
        "optional_skills": ["TypeScript", "Tailwind CSS", "Testing", "Next.js"],
        "education_paths": ["S1 Ilmu Komputer", "Bootcamp Coding", "D3 Teknik Informatika"],
        "salary_min": "Rp5.000.000", "salary_max": "Rp18.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Tinggi", "holland_codes": ["IRC", "ICR"], "pace": "cepat",
        "income_trajectory": "accelerating", "autonomy_level": 4, "ai_displacement_score": 0.15,
        "thrives_on": ["Masalah teknis & sistem", "Masalah kreatif & estetika"],
        "struggles_with": ["Perubahan requirement mendadak", "Debugging rumit"],
        "growth_rate_5yr": "+15-20%", "saturation_risk": "Sedang", "bureaucracy_level": 2,
        "adjacent_careers": ["Backend Developer", "UI/UX Designer", "Mobile Developer"],
        "bridge_careers": ["QA Engineer"],
        "aspiration_careers": ["Tech Lead", "Frontend Architect", "Engineering Manager"],
        "management_track": True, "ic_track": True,
    }),
    _v2_career({
        "title": "Backend Developer", "category": "Teknologi (IT)",
        "description": "Backend Developer mengembangkan logika server, API, dan database yang mendukung aplikasi.",
        "common_tasks": ["Membangun REST API", "Desain database", "Optimasi query", "Arsitektur sistem", "Deployment"],
        "required_skills": ["Python/Node.js", "SQL", "REST API", "Git"],
        "optional_skills": ["Docker", "Cloud (AWS/GCP)", "Message Queue", "GraphQL"],
        "education_paths": ["S1 Ilmu Komputer", "Bootcamp Coding"],
        "salary_min": "Rp5.000.000", "salary_max": "Rp20.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Tinggi", "holland_codes": ["IRC", "ICR"], "pace": "cepat",
        "income_trajectory": "accelerating", "autonomy_level": 4, "ai_displacement_score": 0.15,
        "thrives_on": ["Masalah teknis & sistem", "Masalah organisasi & efisiensi"],
        "struggles_with": ["Tekanan deadline ketat", "On-call incident"], "growth_rate_5yr": "+15-20%",
        "adjacent_careers": ["DevOps Engineer", "Data Engineer", "Cloud Architect"],
        "aspiration_careers": ["Software Architect", "Engineering Manager", "CTO"],
        "management_track": True, "ic_track": True,
    }),
    _v2_career({
        "title": "UI/UX Designer", "category": "Teknologi (IT)",
        "description": "UI/UX Designer merancang antarmuka dan pengalaman pengguna yang intuitif dan menarik.",
        "common_tasks": ["Riset pengguna", "Wireframing", "Pembuatan prototipe", "Usability testing", "Desain sistem"],
        "required_skills": ["Figma", "Design Thinking", "Riset Pengguna"],
        "optional_skills": ["HTML/CSS", "Motion Design", "Illustrator", "Prototyping"],
        "education_paths": ["S1 Desain Komunikasi Visual", "Bootcamp UI/UX", "S1 Psikologi"],
        "salary_min": "Rp5.500.000", "salary_max": "Rp16.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Tinggi", "holland_codes": ["ASI", "AIS"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 4, "ai_displacement_score": 0.20,
        "thrives_on": ["Masalah kreatif & estetika", "Masalah sosial & kemanusiaan"],
        "struggles_with": ["Stakeholder subjective feedback", "Design handoff"],
        "growth_rate_5yr": "+12-18%", "saturation_risk": "Sedang", "work_life_balance": 4,
        "adjacent_careers": ["Frontend Developer", "Product Manager", "Graphic Designer"],
        "aspiration_careers": ["Design Lead", "Product Designer", "UX Research Lead"],
    }),
    _v2_career({
        "title": "Data Analyst", "category": "Teknologi (IT)",
        "description": "Data Analyst mengolah data untuk menghasilkan insight yang mendukung keputusan bisnis.",
        "common_tasks": ["Pengumpulan data", "Pembersihan data", "Visualisasi", "Pelaporan", "Dashboard"],
        "required_skills": ["SQL", "Excel", "Python/R", "Visualisasi Data"],
        "optional_skills": ["Tableau/Power BI", "Machine Learning", "Statistika"],
        "education_paths": ["S1 Statistika", "S1 Matematika", "S1 Sistem Informasi"],
        "salary_min": "Rp5.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["IRC", "I"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 3, "ai_displacement_score": 0.35,
        "thrives_on": ["Masalah teknis & sistem", "Masalah organisasi & efisiensi"],
        "struggles_with": ["Data quality issues", "Stakeholder tidak paham data"],
        "growth_rate_5yr": "+10-15%", "saturation_risk": "Sedang",
        "adjacent_careers": ["Data Scientist", "Business Analyst", "BI Developer"],
        "aspiration_careers": ["Data Science Lead", "Data Engineer", "Analytics Manager"],
    }),
    _v2_career({
        "title": "Data Scientist", "category": "Teknologi (IT)",
        "description": "Data Scientist menggunakan machine learning dan analisis statistik untuk memecahkan masalah kompleks.",
        "common_tasks": ["Eksplorasi data", "Pembangunan model ML", "Evaluasi model", "Deployment", "A/B testing"],
        "required_skills": ["Python", "Machine Learning", "Statistika", "SQL"],
        "optional_skills": ["Deep Learning", "Cloud Platform", "MLOps"],
        "education_paths": ["S1 Ilmu Komputer", "S1 Matematika/Statistika", "S2 Data Science"],
        "salary_min": "Rp8.000.000", "salary_max": "Rp30.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["I", "IRC"], "pace": "sedang",
        "income_trajectory": "accelerating", "autonomy_level": 4, "ai_displacement_score": 0.25,
        "thrives_on": ["Masalah sains & penemuan", "Masalah teknis & sistem"],
        "struggles_with": ["Model tidak kovergen", "Data labeling berkualitas"],
        "growth_rate_5yr": "+20-30%", "saturation_risk": "Rendah",
        "adjacent_careers": ["Data Analyst", "ML Engineer", "Data Engineer"],
        "aspiration_careers": ["Data Science Director", "AI Researcher", "Chief Data Officer"],
    }),
    _v2_career({
        "title": "Mobile Developer", "category": "Teknologi (IT)",
        "description": "Mobile Developer membangun aplikasi mobile untuk Android dan iOS.",
        "common_tasks": ["Mengembangkan fitur aplikasi", "Integrasi API", "Testing", "Rilis ke app store", "Code review"],
        "required_skills": ["Kotlin/Swift", "API Integration", "Git"],
        "optional_skills": ["Flutter/React Native", "UI/UX", "CI/CD"],
        "education_paths": ["S1 Ilmu Komputer", "Bootcamp Mobile"],
        "salary_min": "Rp6.000.000", "salary_max": "Rp20.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Tinggi", "holland_codes": ["IRC", "R"], "pace": "cepat",
        "income_trajectory": "accelerating", "autonomy_level": 4, "ai_displacement_score": 0.15,
        "thrives_on": ["Masalah teknis & sistem", "Masalah kreatif & estetika"],
        "struggles_with": ["Fragmentasi device", "App store review process"],
        "growth_rate_5yr": "+10-15%", "saturation_risk": "Sedang",
        "adjacent_careers": ["Frontend Developer", "Backend Developer", "QA Engineer"],
        "aspiration_careers": ["Mobile Architect", "Engineering Manager", "Tech Lead"],
    }),
    _v2_career({
        "title": "Cyber Security Analyst", "category": "Teknologi (IT)",
        "description": "Cyber Security Analyst melindungi sistem dan data organisasi dari ancaman siber.",
        "common_tasks": ["Monitoring keamanan", "Penetration testing", "Incident response", "Security audit", "Patch management"],
        "required_skills": ["Jaringan", "Sistem Operasi", "Keamanan Informasi"],
        "optional_skills": ["Sertifikasi CEH/CISSP", "Python", "Forensik Digital"],
        "education_paths": ["S1 Ilmu Komputer", "S1 Keamanan Informasi", "Sertifikasi"],
        "salary_min": "Rp7.000.000", "salary_max": "Rp25.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Sedang", "holland_codes": ["IRC", "RI"], "pace": "sedang",
        "income_trajectory": "accelerating", "autonomy_level": 4, "ai_displacement_score": 0.10,
        "thrives_on": ["Masalah teknis & sistem", "Masalah keamanan & risiko"],
        "struggles_with": ["Alert fatigue", "Rapid threat landscape changes"],
        "growth_rate_5yr": "+25-35%", "saturation_risk": "Rendah",
        "adjacent_careers": ["Network Engineer", "IT Support", "DevOps Engineer"],
        "bridge_careers": ["IT Support"],
        "aspiration_careers": ["Security Architect", "CISO", "Penetration Testing Lead"],
    }),
    _v2_career({
        "title": "DevOps Engineer", "category": "Teknologi (IT)",
        "description": "DevOps Engineer mengelola infrastruktur dan pipeline deployment untuk pengembangan software.",
        "common_tasks": ["CI/CD pipeline", "Container management", "Infrastructure as Code", "Monitoring", "Incident response"],
        "required_skills": ["Linux", "Docker", "CI/CD", "Cloud Services"],
        "optional_skills": ["Kubernetes", "Terraform", "Ansible"],
        "education_paths": ["S1 Ilmu Komputer", "Bootcamp DevOps"],
        "salary_min": "Rp8.000.000", "salary_max": "Rp25.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Tinggi", "holland_codes": ["RCI", "R"], "pace": "cepat",
        "income_trajectory": "accelerating", "autonomy_level": 4, "ai_displacement_score": 0.20,
        "thrives_on": ["Masalah teknis & sistem", "Masalah organisasi & efisiensi"],
        "struggles_with": ["On-call disruptions", "Legacy system migration"],
        "growth_rate_5yr": "+15-20%", "saturation_risk": "Rendah",
        "adjacent_careers": ["Backend Developer", "Cloud Engineer", "SRE"],
        "aspiration_careers": ["Platform Engineer", "Cloud Architect", "Infrastructure Director"],
    }),
    _v2_career({
        "title": "QA Engineer", "category": "Teknologi (IT)",
        "description": "QA Engineer memastikan kualitas software melalui pengujian manual dan otomatis.",
        "common_tasks": ["Membuat test case", "Manual testing", "Automation testing", "Bug tracking", "Regression testing"],
        "required_skills": ["Testing Methodology", "Bug Tracking", "SQL"],
        "optional_skills": ["Selenium/Cypress", "Python", "CI/CD"],
        "education_paths": ["S1 Ilmu Komputer", "Bootcamp QA", "D3 Teknik Informatika"],
        "salary_min": "Rp4.500.000", "salary_max": "Rp14.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["CRI", "CR"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 3, "ai_displacement_score": 0.30,
        "thrives_on": ["Masalah organisasi & efisiensi", "Masalah teknis & sistem"],
        "struggles_with": ["Flaky tests", "Manually repetitive testing"],
        "growth_rate_5yr": "+8-12%", "saturation_risk": "Sedang",
        "adjacent_careers": ["Software Developer", "DevOps Engineer", "Product Manager"],
        "bridge_careers": ["Frontend Developer", "Backend Developer"],
        "aspiration_careers": ["QA Lead", "Test Architect", "Engineering Manager"],
    }),
    _v2_career({
        "title": "IT Support", "category": "Teknologi (IT)",
        "description": "IT Support memberikan bantuan teknis kepada pengguna dan memelihara infrastruktur IT.",
        "common_tasks": ["Troubleshooting hardware/software", "Instalasi sistem", "Manajemen jaringan", "Ticketing", "User training"],
        "required_skills": ["Windows/Linux", "Jaringan Dasar", "Troubleshooting"],
        "optional_skills": ["Database", "Cloud Basic", "Sertifikasi IT"],
        "education_paths": ["D3 Teknik Informatika", "S1 Sistem Informasi", "Sertifikasi"],
        "salary_min": "Rp3.500.000", "salary_max": "Rp8.000.000", "market_prospect": "Sedang", "ai_risk": "Rendah",
        "remote_availability": "Sedang", "holland_codes": ["R", "CR"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 3, "ai_displacement_score": 0.20,
        "thrives_on": ["Masalah teknis & sistem", "Masalah sosial & kemanusiaan"],
        "struggles_with": ["End user frustration", "Underappreciated work"],
        "growth_rate_5yr": "+5-8%", "saturation_risk": "Sedang",
        "bridge_careers": ["Cyber Security Analyst", "Network Engineer", "Cloud Engineer"],
        "aspiration_careers": ["IT Manager", "Infrastructure Lead", "Service Desk Manager"],
    }),
])

# ──────────────────────────────────────────
# CREATIVE & MEDIA
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Content Creator", "category": "Kreatif & Media",
        "description": "Content Creator memproduksi konten digital untuk platform media sosial dan website.",
        "common_tasks": ["Riset topik", "Produksi konten", "Editing", "Analisis engagement", "Content calendar"],
        "required_skills": ["Menulis", "Fotografi/Video", "Social Media", "Editing"],
        "optional_skills": ["SEO", "Copywriting", "Public Speaking"],
        "education_paths": ["S1 Komunikasi", "S1 Desain", "Otodidak/Bootcamp"],
        "salary_min": "Rp3.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["A", "AE", "AS"], "pace": "cepat",
        "income_trajectory": "variable", "autonomy_level": 5, "ai_displacement_score": 0.35,
        "thrives_on": ["Masalah kreatif & estetika", "Masalah sosial & kemanusiaan"],
        "struggles_with": ["Algorithm changes", "Income instability", "Burnout"],
        "growth_rate_5yr": "+15-25%", "saturation_risk": "Tinggi", "work_life_balance": 2,
        "adjacent_careers": ["Social Media Specialist", "Copywriter", "Video Editor"],
        "aspiration_careers": ["Content Strategist", "Creative Director", "Media Entrepreneur"],
        "entrepreneurial_exit": "Tinggi",
    }),
    _v2_career({
        "title": "Graphic Designer", "category": "Kreatif & Media",
        "description": "Graphic Designer menciptakan desain visual untuk media cetak dan digital.",
        "common_tasks": ["Desain logo/branding", "Layout cetak/digital", "Ilustrasi", "Typography", "Asset preparation"],
        "required_skills": ["Adobe Photoshop", "Adobe Illustrator", "Typography", "Warna"],
        "optional_skills": ["Motion Design", "3D", "Photography"],
        "education_paths": ["S1 Desain Komunikasi Visual", "D3 Desain Grafis"],
        "salary_min": "Rp4.000.000", "salary_max": "Rp12.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["A", "AS"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 4, "ai_displacement_score": 0.40,
        "thrives_on": ["Masalah kreatif & estetika", "Masalah visual & komunikasi"],
        "struggles_with": ["Revisi tak terbatas", "Subjective feedback tanpa brief"],
        "growth_rate_5yr": "+5-10%", "saturation_risk": "Tinggi",
        "adjacent_careers": ["UI/UX Designer", "Content Creator", "Art Director"],
        "aspiration_careers": ["Art Director", "Creative Director", "Design Lead"],
        "entrepreneurial_exit": "Sedang",
    }),
    _v2_career({
        "title": "Video Editor", "category": "Kreatif & Media",
        "description": "Video Editor mengedit dan memproduksi konten video untuk berbagai platform.",
        "common_tasks": ["Editing video", "Color grading", "Sound design", "Efek visual", "Storyboarding"],
        "required_skills": ["Adobe Premiere Pro", "After Effects", "Storytelling"],
        "optional_skills": ["Motion Graphics", "Color Grading", "Videography"],
        "education_paths": ["S1 Film/Televisi", "D3 Multimedia", "Bootcamp"],
        "salary_min": "Rp4.000.000", "salary_max": "Rp12.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["A", "AR"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 4, "ai_displacement_score": 0.35,
        "thrives_on": ["Masalah kreatif & estetika", "Masalah teknis & sistem"],
        "struggles_with": ["Tight deadlines", "Creative block", "Hardware intensive"],
        "growth_rate_5yr": "+8-12%", "saturation_risk": "Sedang",
        "adjacent_careers": ["Content Creator", "Motion Designer", "Videographer"],
        "aspiration_careers": ["Post Production Lead", "Creative Director", "Film Director"],
    }),
    _v2_career({
        "title": "Social Media Specialist", "category": "Kreatif & Media",
        "description": "Social Media Specialist mengelola strategi konten dan engagement di platform media sosial.",
        "common_tasks": ["Perencanaan konten", "Copywriting", "Analisis metrics", "Community management", "Ads management"],
        "required_skills": ["Social Media Platform", "Copywriting", "Analytics", "Content Planning"],
        "optional_skills": ["Graphic Design", "Videography", "SEO"],
        "education_paths": ["S1 Komunikasi", "S1 Marketing", "Bootcamp"],
        "salary_min": "Rp4.000.000", "salary_max": "Rp10.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["E", "EA", "S"], "pace": "cepat",
        "income_trajectory": "linear", "autonomy_level": 3, "ai_displacement_score": 0.30,
        "thrives_on": ["Masalah sosial & kemanusiaan", "Masalah kreatif & estetika"],
        "struggles_with": ["24/7 engagement pressure", "Algorithm dependency"],
        "growth_rate_5yr": "+10-15%", "saturation_risk": "Sedang",
        "adjacent_careers": ["Content Creator", "Digital Marketing", "Copywriter"],
        "aspiration_careers": ["Social Media Manager", "Content Strategist", "Marketing Director"],
    }),
])

# ──────────────────────────────────────────
# HEALTHCARE
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Dokter Umum", "category": "Kesehatan",
        "description": "Dokter Umum mendiagnosis dan menangani penyakit umum serta memberikan pelayanan kesehatan primer.",
        "common_tasks": ["Pemeriksaan pasien", "Diagnosis", "Resep obat", "Edukasi kesehatan", "Rujukan spesialis"],
        "required_skills": ["Pengetahuan Medis", "Diagnosis", "Komunikasi", "Empati"],
        "optional_skills": ["Manajemen Klinik", "Penelitian", "Bahasa Asing"],
        "education_paths": ["S1 Kedokteran + Profesi Dokter", "PPDS (Spesialisasi)"],
        "salary_min": "Rp7.000.000", "salary_max": "Rp25.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Rendah", "holland_codes": ["SI", "S"], "pace": "cepat",
        "income_trajectory": "linear", "autonomy_level": 4, "ai_displacement_score": 0.10,
        "thrives_on": ["Masalah sosial & kemanusiaan", "Masalah sains & penemuan"],
        "struggles_with": ["Emotional burnout", "Long hours", "Malpractice risk"],
        "growth_rate_5yr": "+5-10%", "saturation_risk": "Rendah", "work_life_balance": 2,
        "adjacent_careers": ["Peneliti Medis", "Dosen Kedokteran", "Manajemen RS"],
        "aspiration_careers": ["Dokter Spesialis", "Kepala Rumah Sakit", "Peneliti Senior"],
        "credential_weight": 5,
    }),
    _v2_career({
        "title": "Perawat", "category": "Kesehatan",
        "description": "Perawat memberikan asuhan keperawatan kepada pasien di rumah sakit dan fasilitas kesehatan.",
        "common_tasks": ["Perawatan pasien", "Administrasi obat", "Monitoring vital sign", "Edukasi pasien", "Dokumentasi"],
        "required_skills": ["Keperawatan Dasar", "Komunikasi", "Emergency Response"],
        "optional_skills": ["Manajemen Ruangan", "Bahasa Asing"],
        "education_paths": ["D3 Keperawatan", "S1 Keperawatan + Ners"],
        "salary_min": "Rp3.500.000", "salary_max": "Rp10.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Rendah", "holland_codes": ["S", "SI"], "pace": "cepat",
        "income_trajectory": "linear", "autonomy_level": 2, "ai_displacement_score": 0.05,
        "thrives_on": ["Masalah sosial & kemanusiaan", "Masalah kesehatan & perawatan"],
        "struggles_with": ["Shift malam", "Beban pasien tinggi", "Burnout emosional"],
        "growth_rate_5yr": "+8-12%", "saturation_risk": "Rendah", "work_life_balance": 2,
        "adjacent_careers": ["Bidan", "Manajemen RS", "Dosen Keperawatan"],
        "aspiration_careers": ["Kepala Ruangan", "Keperawatan Spesialis", "Manajer Keperawatan"],
    }),
    _v2_career({
        "title": "Apoteker", "category": "Kesehatan",
        "description": "Apoteker menyiapkan dan memberikan obat serta memberikan informasi mengenai penggunaan obat.",
        "common_tasks": ["Peracikan obat", "Konseling obat", "Manajemen apotek", "Cek interaksi obat", "Stok obat"],
        "required_skills": ["Farmakologi", "Manajemen Obat", "Komunikasi"],
        "optional_skills": ["Penelitian", "Manajemen Bisnis"],
        "education_paths": ["S1 Farmasi + Profesi Apoteker"],
        "salary_min": "Rp5.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Rendah", "holland_codes": ["I", "IC", "S"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 3, "ai_displacement_score": 0.15,
        "thrives_on": ["Masalah sains & penemuan", "Masalah sosial & kemanusiaan"],
        "struggles_with": ["Routine dispensing", "Customer complaints"],
        "growth_rate_5yr": "+5-8%", "saturation_risk": "Rendah", "work_life_balance": 3,
        "adjacent_careers": ["Peneliti Farmasi", "Dosen Farmasi", "Regulatory Affairs"],
        "aspiration_careers": ["Apoteker Kepala", "Manager Farmasi", "Peneliti Senior"],
    }),
])

# ──────────────────────────────────────────
# EDUCATION
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Guru SD", "category": "Pendidikan",
        "description": "Guru SD mengajar mata pelajaran dasar dan membimbing perkembangan siswa sekolah dasar.",
        "common_tasks": ["Mengajar", "Membuat RPP", "Evaluasi siswa", "Komunikasi orang tua", "Bimbingan karakter"],
        "required_skills": ["Pedagogi", "Komunikasi", "Kesabaran", "Kreativitas"],
        "optional_skills": ["Bimbingan Konseling", "Teknologi Pendidikan"],
        "education_paths": ["S1 PGSD", "S1 Pendidikan", "PPG"],
        "salary_min": "Rp2.500.000", "salary_max": "Rp7.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Rendah", "holland_codes": ["S", "SA"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 3, "ai_displacement_score": 0.05,
        "thrives_on": ["Masalah sosial & kemanusiaan", "Masalah pendidikan & pengajaran"],
        "struggles_with": ["Classroom management", "Administrasi berat", "Gaji rendah"],
        "growth_rate_5yr": "+3-5%", "saturation_risk": "Rendah", "work_life_balance": 4,
        "adjacent_careers": ["Guru BK", "Dosen", "Konsultan Pendidikan"],
        "aspiration_careers": ["Kepala Sekolah", "Pengawas Pendidikan", "Dosen"],
    }),
    _v2_career({
        "title": "Dosen", "category": "Pendidikan",
        "description": "Dosen mengajar dan melakukan penelitian di perguruan tinggi.",
        "common_tasks": ["Mengajar", "Penelitian", "Publikasi ilmiah", "Pengabdian masyarakat", "Bimbingan mahasiswa"],
        "required_skills": ["Penelitian", "Publikasi", "Pengajaran", "Komunikasi"],
        "optional_skills": ["Bahasa Asing", "Statistika", "Jurnalistik Ilmiah"],
        "education_paths": ["S2 (Minimal)", "S3", "Sertifikasi Dosen"],
        "salary_min": "Rp4.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang",
        "remote_availability": "Sedang", "holland_codes": ["I", "IS", "S"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 5, "ai_displacement_score": 0.15,
        "thrives_on": ["Masalah sains & penemuan", "Masalah sosial & kemanusiaan"],
        "struggles_with": ["Tekanan publikasi", "Politik akademik", "Birokrasi"],
        "growth_rate_5yr": "+5-8%", "saturation_risk": "Sedang", "work_life_balance": 3,
        "adjacent_careers": ["Peneliti", "Konsultan", "Content Creator Edukasi"],
        "aspiration_careers": ["Guru Besar", "Rektor", "Peneliti Utama"],
    }),
])

# ──────────────────────────────────────────
# BUSINESS & MARKETING
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Digital Marketing", "category": "Bisnis & Marketing",
        "description": "Digital Marketing mengelola strategi pemasaran online untuk meningkatkan brand awareness dan penjualan.",
        "common_tasks": ["SEO/SEM", "Social media ads", "Email marketing", "Analytics", "Content strategy"],
        "required_skills": ["SEO", "Google Ads", "Social Media Ads", "Analytics"],
        "optional_skills": ["Copywriting", "Design", "Content Strategy"],
        "education_paths": ["S1 Marketing", "S1 Komunikasi", "Bootcamp Digital Marketing"],
        "salary_min": "Rp4.500.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["E", "EA", "EC"], "pace": "cepat",
        "income_trajectory": "accelerating", "autonomy_level": 3, "ai_displacement_score": 0.30,
        "thrives_on": ["Masalah kreatif & estetika", "Masalah organisasi & efisiensi"],
        "struggles_with": ["ROI attribution", "Algorithm updates", "Budget constraints"],
        "growth_rate_5yr": "+12-18%", "saturation_risk": "Sedang",
        "adjacent_careers": ["Social Media Specialist", "Content Creator", "Sales"],
        "aspiration_careers": ["Marketing Manager", "Growth Lead", "CMO"],
        "management_track": True,
    }),
    _v2_career({
        "title": "Wirausaha", "category": "Bisnis & Marketing",
        "description": "Wirausaha memulai dan mengelola bisnis sendiri, dari perencanaan hingga eksekusi.",
        "common_tasks": ["Perencanaan bisnis", "Manajemen operasional", "Pemasaran", "Keuangan", "Networking"],
        "required_skills": ["Leadership", "Manajemen", "Pemasaran", "Problem Solving"],
        "optional_skills": ["Digital Marketing", "Keuangan", "Networking"],
        "education_paths": ["Pengalaman Lapangan", "S1 Manajemen/Bisnis", "Bootcamp"],
        "salary_min": "Rp2.000.000", "salary_max": "Rp50.000.000", "market_prospect": "Variatif", "ai_risk": "Sedang",
        "remote_availability": "Tinggi", "holland_codes": ["E", "EA", "ES"], "pace": "cepat",
        "income_trajectory": "variable", "autonomy_level": 5, "ai_displacement_score": 0.20,
        "thrives_on": ["Masalah organisasi & efisiensi", "Masalah keuangan & alokasi"],
        "struggles_with": ["Income instability", "Loneliness", "Decision fatigue"],
        "growth_rate_5yr": "Variatif", "saturation_risk": "Sedang", "work_life_balance": 1,
        "adjacent_careers": ["Konsultan Bisnis", "Digital Marketing", "Sales"],
        "aspiration_careers": ["Serial Entrepreneur", "Investor", "Mentor"],
        "entrepreneurial_exit": "Tinggi",
    }),
])

# ──────────────────────────────────────────
# FINANCE & LAW
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Akuntan", "category": "Keuangan & Hukum",
        "description": "Akuntan mengelola pencatatan keuangan, audit, dan pelaporan pajak untuk perusahaan atau klien.",
        "common_tasks": ["Pembukuan", "Laporan keuangan", "Audit", "Perpajakan", "Rekonsiliasi"],
        "required_skills": ["Akuntansi", "Pajak", "Excel", "Software Akuntansi"],
        "optional_skills": ["Audit", "Analisis Keuangan", "SAP/Oracle"],
        "education_paths": ["S1 Akuntansi", "PPAk (Pendidikan Profesi Akuntansi)"],
        "salary_min": "Rp4.500.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Sedang",
        "remote_availability": "Sedang", "holland_codes": ["C", "CE", "I"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 3, "ai_displacement_score": 0.40,
        "thrives_on": ["Masalah organisasi & efisiensi", "Masalah keuangan & alokasi"],
        "struggles_with": ["Deadline pajak", "Perubahan regulasi", "Routine work"],
        "growth_rate_5yr": "+5-8%", "saturation_risk": "Sedang",
        "adjacent_careers": ["Financial Analyst", "Auditor", "Tax Consultant"],
        "aspiration_careers": ["Finance Manager", "CFO", "Partner Accounting Firm"],
        "management_track": True,
    }),
])

# ──────────────────────────────────────────
# GOVERNMENT & BUMN
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "PNS Administrasi", "category": "Pemerintahan & BUMN",
        "description": "PNS Administrasi melaksanakan tugas ketatausahaan dan pelayanan publik di instansi pemerintah.",
        "common_tasks": ["Administrasi surat", "Pelayanan publik", "Pelaporan", "Kearsipan", "Koordinasi antar dinas"],
        "required_skills": ["Administrasi", "Komunikasi", "Microsoft Office"],
        "optional_skills": ["Manajemen Arsip", "Hukum Administrasi"],
        "education_paths": ["S1 Semua Jurusan", "Tes CPNS"],
        "salary_min": "Rp3.000.000", "salary_max": "Rp10.000.000", "market_prospect": "Stabil", "ai_risk": "Rendah",
        "remote_availability": "Rendah", "holland_codes": ["C", "CE", "S"], "pace": "lambat",
        "income_trajectory": "linear", "autonomy_level": 2, "ai_displacement_score": 0.15,
        "thrives_on": ["Masalah organisasi & efisiensi", "Masalah sosial & kemanusiaan"],
        "struggles_with": ["Birokrasi berlapis", "Kurang tantangan", "Politik kantor"],
        "growth_rate_5yr": "Stabil", "saturation_risk": "Tinggi", "work_life_balance": 5,
        "adjacent_careers": ["BUMN", "Sekretaris", "Manajemen Publik"],
        "aspiration_careers": ["Kepala Dinas", "Sekretaris Daerah", "Pejabat Eselon"],
        "bureaucracy_level": 5,
    }),
])

# ──────────────────────────────────────────
# NON-IT ENGINEERING
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Teknik Sipil", "category": "Teknik non-IT",
        "description": "Teknik Sipil merancang, membangun, dan memelihara infrastruktur seperti gedung, jembatan, dan jalan.",
        "common_tasks": ["Perencanaan konstruksi", "Pengawasan proyek", "Manajemen material", "Gambar teknis", "Estimasi biaya"],
        "required_skills": ["AutoCAD", "Struktur", "Manajemen Proyek"],
        "optional_skills": ["SAP2000/ETABS", "Revit", "Estimasi Biaya"],
        "education_paths": ["S1 Teknik Sipil"],
        "salary_min": "Rp5.000.000", "salary_max": "Rp15.000.000", "market_prospect": "Tinggi", "ai_risk": "Rendah",
        "remote_availability": "Rendah", "holland_codes": ["R", "RI", "RC"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 3, "ai_displacement_score": 0.15,
        "thrives_on": ["Masalah teknis & sistem", "Masalah fisik & konstruksi"],
        "struggles_with": ["Proyek molor", "Cuaca lapangan", "Safety risk"],
        "growth_rate_5yr": "+8-12%", "saturation_risk": "Sedang", "travel_requirement": "field",
        "adjacent_careers": ["Arsitek", "Manajer Konstruksi", "Quantity Surveyor"],
        "aspiration_careers": ["Project Manager", "Konsultan Senior", "Kontraktor Besar"],
        "management_track": True,
    }),
    _v2_career({
        "title": "Arsitek", "category": "Teknik non-IT",
        "description": "Arsitek merancang bangunan dan ruang yang estetis, fungsional, dan aman.",
        "common_tasks": ["Desain bangunan", "Gambar teknis", "Koordinasi kontraktor", "3D modeling", "Site visit"],
        "required_skills": ["AutoCAD", "SketchUp/Revit", "Desain"],
        "optional_skills": ["3D Rendering", "Sustainable Design", "Manajemen Proyek"],
        "education_paths": ["S1 Arsitektur"],
        "salary_min": "Rp5.000.000", "salary_max": "Rp18.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang",
        "remote_availability": "Sedang", "holland_codes": ["A", "AR", "AI"], "pace": "sedang",
        "income_trajectory": "linear", "autonomy_level": 4, "ai_displacement_score": 0.25,
        "thrives_on": ["Masalah kreatif & estetika", "Masalah teknis & sistem"],
        "struggles_with": ["Revisi klien", "Regulasi perubahan", "Persaingan fee"],
        "growth_rate_5yr": "+5-10%", "saturation_risk": "Sedang",
        "adjacent_careers": ["Interior Designer", "Teknik Sipil", "Urban Planner"],
        "aspiration_careers": ["Arsitek Principal", "Design Director", "Firm Owner"],
        "entrepreneurial_exit": "Sedang",
    }),
])

# ──────────────────────────────────────────
# SERVICES & TOURISM
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Tour Guide", "category": "Jasa & Pariwisata",
        "description": "Tour Guide memandu wisatawan dan memberikan informasi tentang objek wisata.",
        "common_tasks": ["Memandu tur", "Informasi wisata", "Koordinasi logistik", "Bahasa asing", "Handling emergency"],
        "required_skills": ["Bahasa Inggris", "Komunikasi", "Pengetahuan Lokal"],
        "optional_skills": ["Bahasa Asing Lain", "Fotografi", "First Aid"],
        "education_paths": ["D3 Pariwisata", "S1 Pariwisata", "Sertifikasi Pramuwisata"],
        "salary_min": "Rp2.500.000", "salary_max": "Rp8.000.000", "market_prospect": "Sedang", "ai_risk": "Sedang",
        "remote_availability": "Rendah", "holland_codes": ["S", "SE", "A"], "pace": "cepat",
        "income_trajectory": "variable", "autonomy_level": 3, "ai_displacement_score": 0.20,
        "thrives_on": ["Masalah sosial & kemanusiaan", "Masalah komunikasi & pelayanan"],
        "struggles_with": ["Musim sepi", "Turis sulit", "Fisik lelah"],
        "growth_rate_5yr": "+5-10%", "saturation_risk": "Sedang", "travel_requirement": "frequent",
        "adjacent_careers": ["Hospitality", "Event Organizer", "Travel Blogger"],
        "aspiration_careers": ["Tour Manager", "Travel Agent Owner", "Hospitality Manager"],
        "entrepreneurial_exit": "Sedang",
    }),
])

# ──────────────────────────────────────────
# AGRICULTURE
# ──────────────────────────────────────────
INITIAL_CAREERS.extend([
    _v2_career({
        "title": "Petani Modern", "category": "Pertanian & Kelautan",
        "description": "Petani Modern menggunakan teknologi dan metode pertanian terkini untuk meningkatkan hasil panen.",
        "common_tasks": ["Perencanaan tanam", "Penggunaan teknologi pertanian", "Manajemen hasil", "Irigasi", "Pemasaran hasil"],
        "required_skills": ["Agrikultur", "Manajemen", "Teknologi Pertanian"],
        "optional_skills": ["Hidroponik", "IoT", "Pemasaran Digital"],
        "education_paths": ["S1 Agribisnis", "S1 Pertanian", "Pelatihan"],
        "salary_min": "Rp3.000.000", "salary_max": "Rp10.000.000", "market_prospect": "Sedang", "ai_risk": "Rendah",
        "remote_availability": "Rendah", "holland_codes": ["R", "RE", "RI"], "pace": "sedang",
        "income_trajectory": "variable", "autonomy_level": 5, "ai_displacement_score": 0.10,
        "thrives_on": ["Masalah lingkungan & alam", "Masalah pangan & produksi"],
        "struggles_with": ["Cuaca tak menentu", "Harga fluktuatif", "Tenaga kerja"],
        "growth_rate_5yr": "+5-8%", "saturation_risk": "Rendah", "travel_requirement": "field",
        "adjacent_careers": ["Agribisnis", "Teknisi Pertanian", "Food Tech"],
        "aspiration_careers": ["Pengusaha Agrikultur", "Konsultan Pertanian", "Peneliti Pertanian"],
        "entrepreneurial_exit": "Tinggi",
    }),
])

CATEGORIES = [
    "Teknologi (IT)", "Kesehatan", "Pendidikan", "Pemerintahan & BUMN",
    "Kreatif & Media", "Bisnis & Marketing", "Teknik non-IT",
    "Keuangan & Hukum", "Jasa & Pariwisata", "Pertanian & Kelautan"
]
